config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search" 
  get "tag_search" => "tag_searches#search" 
  
  
  devise_for :users
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy,]
  end
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "search", to: "users#search"
    get :follower, on: :member
    get :followerd, on: :member
  end
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :view_counts, dependent: :destroy
  
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  validates :tag,presence:true
  
  # 本の投稿数
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) } 
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) } 
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) } 
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) } 
  scope :created_2days, -> { where(created_at: 2.days.ago.all_day) } 
  scope :created_3days, -> { where(created_at: 3.days.ago.all_day) } 
  scope :created_4days, -> { where(created_at: 4.days.ago.all_day) } 
  scope :created_5days, -> { where(created_at: 5.days.ago.all_day) } 
  scope :created_6days, -> { where(created_at: 6.days.ago.all_day) } 
  
  # paramsの取り出し方
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end


  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    
    belongs_to :user
    belongs_to :book
    
    validates :comment,presence:true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
    belongs_to :user
    belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :group_image
  
  def get_group_image
    (group_image.attached?) ? group_image : 'no_image.jpg'
  end
  
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :message, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followerd, class_name: "User"
  
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image
  # フォローする側 follower
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followerd
  # フォローされる側 followerd
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followerd_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  # DM
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  # 閲覧数
  has_many :view_counts, dependent: :destroy
  # グループ
  has_many :group_users
  has_many :groups, through: :group_users

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)が
    # フォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(follower_id: user.id).present?
  end

# 検索条件分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = Kaminari.paginate_array(@user.books).page(params[:page]).per(5) # ページネーション
    @book = Book.new
    @books2 = @user.books
    # 投稿数の記述
    @today_book =  @books2.created_today
    @yesterday_book = @books2.created_yesterday
    @this_week_book = @books2.created_this_week
    @last_week_book = @books2.created_last_week
    # DMの記述
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end
  
  def follower
    user = User.find(params[:id])
    @users = user.followings
  end
  
  def followerd
    user = User.find(params[:id])
    @users = user.followers
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end
  
  def search
    user = User.find(params[:user_id])
    @search_book = user.books.where(created_at: params[:created_at].to_date.all_day)
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tag_searches_helper.rb
module TagSearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table table-hover'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= link_to image_tag(user.get_profile_image, size: '50x50'), user %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followings.count %></td>
        <td>フォロワー数:<%= user.followers.count %></td>
        <td>
        <% if current_user != user %>
          <% if user.followed_by?(current_user) %>
              <%=link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
          <% else %>
              <%=link_to "フォローする", user_relationships_path(user.id), method: :post %>
          <% end %>
        </td>
            <td><%= link_to 'Show', user %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
	  <th>follows</th>
	  <th><%=link_to user.followings.count, follower_user_path(user.id) %></th>
  </tr>
  <tr>
	  <th>followers</th>
	  <th><%=link_to user.followers.count, followerd_user_path(user.id) %></th>
  </tr>
</table>
　
<div class='row mt-0'>
  <!--フォローボタン-->
  <% if current_user != user %>
    <% if user.followed_by?(current_user) %>
      <%=link_to "フォロー外す", user_relationships_path(user.id), method: :delete ,class: "btn btn-secondary mx-2 p-2" %>
    <% else %>
      <%=link_to "フォローする", user_relationships_path(user.id), method: :post ,class: "btn btn-primary mx-2"%>
    <% end %>
    
    <!--DMボタン-->
    <% if (current_user.followings.include?(user)) && (user.followings.include?(current_user)) %>
      <% if @isRoom == true %>
        <%= link_to "Chat Room", "/rooms/#{roomId}", class: "btn btn-primary" %>
      <% else %>
      <%= form_with(model: @room, local: true) do |f| %>
      <%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, value: user.id %>
      <% end %>
      <%= f.submit "chatを始める", class: "btn btn-primary user-show-chat " %>
    <% end %>
    <% end %>
    <% end %>
    
    <% else %>
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %><br>
  <% end %>
</div>

app/views/users/_search.html.erb
<div>
  <%= form_with url: user_search_path(user), method: :get, class: "row", local: false do |f| %>
    <div class="col-auto pr-2">
      <%= f.date_field :created_at, class: "form-control" %>
    </div>
    <div class="col-auto pl-0">
      <%= f.submit "検索" , class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

<div class="daily_posts_table">
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/follower.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <h2>Followd Users</h2>
    <table class='table'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
            <td><%= user.name %></td>
            <td>フォロー数:<%= user.followings.count %></td>
            <td>フォロワー数:<%= user.followers.count %></td>
            <td>
              <% if current_user != user %>
              <% if user.followed_by?(current_user) %>
                  <%=link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
              <% else %>
                  <%=link_to "フォローする", user_relationships_path(user.id), method: :post %>
              <% end %>
            </td>
            <td><%= link_to 'Show', user %></td>
        <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/followerd.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <h2>Follower Users</h2>
    <table class='table'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
            <td><%= user.name %></td>
            <td>フォロー数:<%= user.followings.count %></td>
            <td>フォロワー数:<%= user.followers.count %></td>
            <td>
              <% if current_user != user %>
              <% if user.followed_by?(current_user) %>
                  <%=link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
              <% else %>
                  <%=link_to "フォローする", user_relationships_path(user.id), method: :post %>
              <% end %>
            </td>
            <td><%= link_to 'Show', user %></td>
        <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
        <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
        <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
        <h2>Users</h2>
        <div><%=link_to "グループを作成する",new_group_path %> | <%=link_to "グループ一覧",groups_path %></div>
        <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$('.daily_posts_table').html(`
  <% if @search_book.present? %>
    <h3>検索結果</h3>
    <div class="card">
      <div class="card-header">投稿数</div>
      <div class="card-body">
        <%= j(@search_book.count) %>
      </div>
    </div>
  <% else %>
    <p>該当する投稿はありません</p>
  <% end %>
`);

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user ,room: Room.new ,entry: Entry.new ,isRoom: @isRoom ,roomId: @roomId %>
      
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
      <!--投稿数検索-->
      <%= render 'search', user: @user %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <%= paginate @books %>

      
      <!--投稿数の表示-->
      <h3>投稿数の前日比・前週比</h3>
      <div class="table_width">
        <table class="table table-bordered">
          <thead>
          <tr>
            <th>今日の投稿数</th>
            <th>昨日の投稿数</th>
            <th>前日比</th>
          </tr>
          </thead>
          <tbody>
            <tr>
          	  <td><%= @today_book.count %></td>
          	  <td><%= @yesterday_book.count %></td>
                  <% if @yesterday_book.count == 0 %>
          	  <td>前日の投稿はなし</td>
                  <% else %>
          	  <td><% @the_day_before =   @today_book.count / @yesterday_book.count  %>
          	  <%= (@the_day_before * 100).round %>%</td>
                  <% end %>
            </tr>
          </tbody>
        </table>
          
        <table class="table table-bordered">
          <thead>
          <tr>
            <th>今週の投稿数</th>
            <th>先週の投稿数</th>
            <th>先週比</th>
          </tr>
          </thead>
          <tbody>
            <tr>
          	  <td><%= @this_week_book.count %></td>
          	  <td><%= @last_week_book.count %></td>
                  <% if @last_week_book.count == 0 %>
          	  <td>先週の投稿はなし</td>
                  <% else %>
          	  <td><% @the_week_before = @this_week_book.count / @last_week_book.count  %>
          	  <%= (@the_week_before * 100).round %>%</td>
                  <% end %>
            </tr>
          </tbody>
        </table>
      </div>  
      
      <!--七日間の投稿数-->
      <h3>7日分の投稿数</h3>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>６日前</th>
            <th>5日前</th>
            <th>4日前</th>
            <th>3日前</th>
            <th>２日前</th>
            <th>昨日</th>
            <th>今日</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @books2.created_6days.count %></td>
            <td><%= @books2.created_5days.count %></td>
            <td><%= @books2.created_4days.count %></td>
            <td><%= @books2.created_3days.count %></td>
            <td><%= @books2.created_2days.count %></td>
            <td><%= @yesterday_book.count %></td>
            <td><%= @today_book.count %></td>
          </tr>
        </tbody>
      </table>
      
    <!--グラフ-->
    <p class="graph-title text-center mb-0 font-weight-bold">7日間の投稿数の比較</p>
    <canvas id="myChart" width="100%" height="40px">
      <script data-turbolinks-eval="false">
        $(document).on("turbolinks:load", function() {
          var ctx = document.getElementById("myChart").getContext('2d');
          var myChart = new Chart(ctx, {
            type: 'line',
            data: {
              labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '昨日', '今日'],
              datasets: [{
                label: "投稿した本の数",
                data: [<%= @books2.created_6days.count %>, <%= @books2.created_5days.count %>, <%= @books2.created_4days.count %>, <%= @books2.created_3days.count %>, <%= @books2.created_2days.count %>, <%= @yesterday_book.count %>, <%= @today_book.count %>],
                backgroundColor: 'rgba(255, 80, 120, 1.0)',
                borderColor: 'rgba(255, 80, 120, 1.0)',
                lineTension: 0.4,
                fill: false
              }]
            },
            options: {
              responsive: true,
              scales: {
                y:{
                  suggestedMin: 0,
                  suggestedMax: 10
                },
                x:{
                  stacked: true
                },
              },
            }
          });
        });
      </script>
    </canvas>
  </div>
</div>