config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search" 
  get "tag_search" => "tag_searches#search" 
  
  
  devise_for :users
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy,]
  end
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "search", to: "users#search"
    get :follower, on: :member
    get :followerd, on: :member
  end
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :view_counts, dependent: :destroy
  
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  validates :tag,presence:true
  
  # 本の投稿数
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) } 
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) } 
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) } 
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) } 
  scope :created_2days, -> { where(created_at: 2.days.ago.all_day) } 
  scope :created_3days, -> { where(created_at: 3.days.ago.all_day) } 
  scope :created_4days, -> { where(created_at: 4.days.ago.all_day) } 
  scope :created_5days, -> { where(created_at: 5.days.ago.all_day) } 
  scope :created_6days, -> { where(created_at: 6.days.ago.all_day) } 
  
  # paramsの取り出し方
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end


  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    
    belongs_to :user
    belongs_to :book
    
    validates :comment,presence:true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
    belongs_to :user
    belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :group_image
  
  def get_group_image
    (group_image.attached?) ? group_image : 'no_image.jpg'
  end
  
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :message, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followerd, class_name: "User"
  
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image
  # フォローする側 follower
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followerd
  # フォローされる側 followerd
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followerd_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  # DM
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  # 閲覧数
  has_many :view_counts, dependent: :destroy
  # グループ
  has_many :group_users
  has_many :groups, through: :group_users

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)が
    # フォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(follower_id: user.id).present?
  end

# 検索条件分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/searches/search.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <table class="table table-hover table-inverse">
      <!--検索対象モデルがUserの時 -->
      <% if @range == "User" %>
      <h2>Users search for "<%= params[:word] %>"</h2>
        <thead>
          <tr>
            <th></th>
            <th>name</th>
            <th>Follow</th>
            <th>Follower</th>
            <th colspan="4"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image, size: '40x40' %></td>
            <td><%= user.name %></td>
            <td>フォロー数:<%= user.followings.count %></td>
            <td>フォロワー数:<%= user.followers.count %></td>
            <td>
            <% if current_user != user %>
              <% if user.followed_by?(current_user) %>
                  <%=link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
              <% else %>
                  <%=link_to "フォローする", user_relationships_path(user.id), method: :post %>
              <% end %>
            </td>
                <td><%= link_to 'Show', user %></td>
              <% end %>
          </tr>
          <% end %>
        </tbody>
      <% elsif @range == "Book" %>
      <h2>Books search for "<%= params[:word] %>"</h2>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th>Tag</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td><%= link_to(book.user) do %>
                  <%= image_tag book.user.get_profile_image, size:'50x50' %>
                  <% end %>
                </td>
                <td><%= link_to book.title,book %></td>
                <td><%= book.body %></td>
                <td><%= book.tag %></td>
                <td>
                    <% if book.favorited_by?(current_user) %>
                      <div class="btn p-0">
                        <%= link_to book_favorites_path(book), method: :delete ,class:"text-danger" do %>
                           ♥<%= book.favorites.count %>
                        <% end %>
                      </div>
                    <% else %>
                      <%= link_to book_favorites_path(book), method: :post,class:"btn p-0 text-primary" do %>
                        ♡<%= book.favorites.count %>
                      <% end %>
                    <% end %>
                  </td>
                <td><%= "コメント数: #{book.book_comments.count}" %></td>
              </tr>
            <% end %>
          </tbody>
      <% else %>
        <!--検索対象モデルがUserではない時(= 検索対象モデルがBookの時) -->
        <h2>Books-Tag search for "<%= params[:word] %>"</h2>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th>Tag</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td><%= link_to(book.user) do %>
                  <%= image_tag book.user.get_profile_image, size:'50x50' %>
                  <% end %>
                </td>
                <td><%= link_to book.title,book %></td>
                <td><%= book.body %></td>
                <td><%= book.tag %></td>
                <td>
                    <% if book.favorited_by?(current_user) %>
                      <div class="btn p-0">
                        <%= link_to book_favorites_path(book), method: :delete ,class:"text-danger" do %>
                           ♥<%= book.favorites.count %>
                        <% end %>
                      </div>
                    <% else %>
                      <%= link_to book_favorites_path(book), method: :post,class:"btn p-0 text-primary" do %>
                        ♡<%= book.favorites.count %>
                      <% end %>
                    <% end %>
                  </td>
                <td><%= "コメント数: #{book.book_comments.count}" %></td>
              </tr>
            <% end %>
          </tbody>

      <% end %>
    </table>
  </div>
</div>